"""Incident API endpoints."""

from __future__ import annotations

from fastapi import APIRouter, Depends, Request

from mythos.api.auth import get_current_subject
from mythos.incident_response.models import Incident

router = APIRouter(prefix="/incidents", tags=["incidents"])


@router.get("", response_model=list[Incident])
async def list_incidents(request: Request, _: str = Depends(get_current_subject)) -> list[Incident]:
    """Lists incidents generated by orchestration."""
    incidents: list[Incident] = []
    for serialized in request.app.state.orchestrator.incidents.values():
        incidents.append(Incident.model_validate_json(serialized))
    return incidents
